### ISSUE TITLE
Make HTTPS optional

### ISSUE THREAD

**Issue by leonardopc** [chrisvel/tududi#12]
SInce I am using a reverse proxy, I have no need to have your application creating/managing SSL certificates for me. Currently it does not work out of the box with traefik. Please make HTTPS optional so that my reverse proxy can take care of that.
Thanks

**Comment by chrisvel** [comment]
Please pull `v0.16` - A flag has been added to conditionally disable or enable the pre-generated SSL `TUDUDI_INTERNAL_SSL_ENABLED`. Check the README.
