### ISSUE TITLE
Internal server error when creating a project without assigning it to an area

### ISSUE THREAD

**Issue by LokiRothbrook** [chrisvel/tududi#44]
if you create a project but do not select an area to assign it to the project page breaks and results in an internal server error

**Comment by LokiRothbrook** [comment]
forgive me for being stupid. used docker commands from docker hub. and just connected the dots that its pulling an old version. docker hub still points to V0.18. this bug is no longer present.

**Comment by chrisvel** [comment]
Thank you for clearing this out!
