### ISSUE TITLE
Docker volume not working

### ISSUE THREAD

**Issue by skyrunner15** [chrisvel/tududi#7]
When I pass this command into docker compose via portainer, no .db is created and a reload of the container wipes the data. I checked folder permissions which have everyone enabled for read/write.

     volumes:
       - /volume1/docker/tududi:/db

**Comment by TheZoker** [comment]
Same here

**Comment by chrisvel** [comment]
@skyrunner15 the path was wrong, the right one is `:/usr/src/app/db`. I have updated the README file. Let me know If this works.

**Comment by skyrunner15** [comment]
Hmm... no dice. Now the instance gets stuck and doesn't start up with 0.6

________________________________

**Comment by chrisvel** [comment]
@skyrunner15 can you please give me a bit more detail? Any error logs, how do you run it? Did it stop working after changing the volume path, after pulling 0.6 or both ?

**Comment by chrisvel** [comment]
Can you try with 0.9 please? I believe it's fixed, I already tested it on 3 machines. 
Just be careful with the volume, I changed the container path: `-v ~/tududi_db:/usr/src/app/tududi_db`

**Comment by TheZoker** [comment]
Works again. But for some reason I always get a "Invalid credentials" error.

This is my test config:
```yml
...
    environment:
      - TUDUDI_USER_EMAIL="mail@example.com"
      - TUDUDI_USER_PASSWORD="test1234"
...
```

Even when I copy paste the credentials, I get this error

And the logs:
```
192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "POST /login HTTP/1.1" 200 2225 0.0021
192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "GET /favicon.ico HTTP/1.1" 302 - 0.0008
192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "GET /login HTTP/1.1" 200 2055 0.0007
W, [2023-11-16T12:11:46.979931 #9]  WARN -- : Invalid credentials for user with email mail@example.com
```

**Comment by skyrunner15** [comment]
I deleted the files in the persistent storage and the app loads fine for me in 0.9. I see the "production.sqlite3" file was created successfully. What doesn't work is the reverse proxy using HTTPS but that's another story :)

**Comment by skyrunner15** [comment]
I will say this is coming along nicely! Using it for work today and fingers crossed my data stays here 😄

**Comment by skyrunner15** [comment]
> Works again. But for some reason I always get a "Invalid credentials" error.
> 
> This is my test config:
> 
> ```yaml
> ...
>     environment:
>       - TUDUDI_USER_EMAIL="mail@example.com"
>       - TUDUDI_USER_PASSWORD="test1234"
> ...
> ```
> 
> Even when I copy paste the credentials, I get this error
> 
> And the logs:
> 
> ```
> 192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "POST /login HTTP/1.1" 200 2225 0.0021
> 192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "GET /favicon.ico HTTP/1.1" 302 - 0.0008
> 192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "GET /login HTTP/1.1" 200 2055 0.0007
> W, [2023-11-16T12:11:46.979931 #9]  WARN -- : Invalid credentials for user with email mail@example.com
> ```

@TheZoker - did you use the right base 64 session key in the environment variables?

- TUDUDI_SESSION_SECRET=

**Comment by chrisvel** [comment]
> Works again. But for some reason I always get a "Invalid credentials" error.
> 
> This is my test config:
> 
> ```yaml
> ...
>     environment:
>       - TUDUDI_USER_EMAIL="mail@example.com"
>       - TUDUDI_USER_PASSWORD="test1234"
> ...
> ```
> 
> Even when I copy paste the credentials, I get this error
> 
> And the logs:
> 
> ```
> 192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "POST /login HTTP/1.1" 200 2225 0.0021
> 192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "GET /favicon.ico HTTP/1.1" 302 - 0.0008
> 192.168.2.90 - - [16/Nov/2023:12:11:37 +0000] "GET /login HTTP/1.1" 200 2055 0.0007
> W, [2023-11-16T12:11:46.979931 #9]  WARN -- : Invalid credentials for user with email mail@example.com
> ```

At this stage I'd suggest you rm the production.sqlite3 file manually from your local directory or just remove the docker volume. Then stop and re-run the command and it will work.

**Comment by TheZoker** [comment]
> @TheZoker - did you use the right base 64 session key in the environment variables?
> 
> * TUDUDI_SESSION_SECRET=

Yes I set it using the openssl command.
Something like this:
```
...
    environment:
      - TUDUDI_USER_EMAIL="mail@example.com"
      - TUDUDI_USER_PASSWORD="test1234"
      - TUDUDI_SESSION_SECRET="bf8bb1876432955442dbf2aedeb3f743c9f55a033d9f31dbeba6ff119ab1ee0cc4a5032364c49f0fa9966b344c221735ae9817dc20a08008f72ed2a367dc9914"
...
```

> At this stage I'd suggest you rm the production.sqlite3 file manually from your local directory or just remove the docker volume. Then stop and re-run the command and it will work.

I already did this. Removed all the files, deleted the container and image and restarted everything. But still the same issue

Anything else I can test?

**Comment by chrisvel** [comment]
> > @TheZoker - did you use the right base 64 session key in the environment variables?
> > 
> > * TUDUDI_SESSION_SECRET=
> 
> Yes I set it using the openssl command. Something like this:
> 
> ```
> ...
>     environment:
>       - TUDUDI_USER_EMAIL="mail@example.com"
>       - TUDUDI_USER_PASSWORD="test1234"
>       - TUDUDI_SESSION_SECRET="bf8bb1876432955442dbf2aedeb3f743c9f55a033d9f31dbeba6ff119ab1ee0cc4a5032364c49f0fa9966b344c221735ae9817dc20a08008f72ed2a367dc9914"
> ...
> ```
> 
> > At this stage I'd suggest you rm the production.sqlite3 file manually from your local directory or just remove the docker volume. Then stop and re-run the command and it will work.
> 
> I already did this. Removed all the files, deleted the container and image and restarted everything. But still the same issue
> 
> Anything else I can test?

Did you change the password? The user is created the first time and then If you change it in the command it doesn't change in the database. 

An alternative is to do a `docker ps` to get the container id and then `docker exec -it <docker_id> rake console`. Then `User.last.update(password: "mynewpassword")`. It should output `=> true`. Then `exit` and your new pass should work.

**Comment by TheZoker** [comment]
I was never able to login, so I don't think I changed the password anywhere. 

When I run the update password function, this error happens:
![image](https://github.com/chrisvel/tududi/assets/1368405/c8859026-be45-4e84-8faf-4b13762159cb)

**Comment by chrisvel** [comment]
> I was never able to login, so I don't think I changed the password anywhere.
> 
> When I run the update password function, this error happens: ![image](https://user-images.githubusercontent.com/1368405/283493548-c8859026-be45-4e84-8faf-4b13762159cb.png)

Are you using the latest image ?

**Comment by TheZoker** [comment]
I'm using this version:
```
image: chrisvel/tududi:0.9
```

**Comment by chrisvel** [comment]
Can you try running a `docker exec -it <docker_id> rake db:migrate` and then try to login again ?

**Comment by chrisvel** [comment]
> I'm using this version:
> 
> ```
> image: chrisvel/tududi:0.9
> ```

Can you try to run `docker exec -it <container_id> rake db:migrate` ?

**Comment by TheZoker** [comment]
Done! Command went trough without any output

Thanks for your help BTW, really appreciate it, that you take your time to help me :)

**Comment by chrisvel** [comment]
No worries, thanks for your feedback!
